# Infra labels
github:
- all:
  - changed-files:
    - any-glob-to-any-file: ".github/**/*"

github/workflows:
- all:
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**/*"

github/templates:
- all:
  - changed-files:
    - any-glob-to-any-file: ".github/ISSUE_TEMPLATE/**/*"

release:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "CHANGELOG.md"
      - "latest.json"

# Documentation labels
docs/config:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - ".gitignore"
      - "*.config.*"
      - "jsconfig.*"

docs/deps:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "package.json"
      - "pnpm-lock.yaml"

docs/site:
- all:
  - changed-files:
    - any-glob-to-any-file: "docs/**/*"

docs/components:
- all:
  - changed-files:
    - any-glob-to-any-file: 
      - "docs/src/components/**/*"
      - "docs/app/**/*"

docs/content:
- all:
  - changed-files:
    - any-glob-to-any-file: "docs/src/content/**/*"

docs/assets:
- all:
  - changed-files:
    - any-glob-to-any-file: "docs/public/**/*"

# React specific labels
frontend:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/**/*"

frontend/components:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/**/*"

frontend/states:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/contexts/**/*"

frontend/ui:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/ui/**/*"

frontend/hooks:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/hooks/**/*"

frontend/i18n:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/i18n/**/*"

frontend/pages:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/pages/**/*"

frontend/styles:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/styles/**/*"

frontend/utils:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/utils/**/*"

frontend/assets:
- all:
  - changed-files:
    - any-glob-to-any-file: "public/**/*"

# Tauri specific labels
tauri:
- all:
  - changed-files:
    - any-glob-to-any-file: "src-tauri/**/*"

tauri/core:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/build.rs"
      - "src-tauri/src/main.rs"
      - "src-tauri/src/lib.rs"

tauri/deps:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/Cargo.lock"
      - "src-tauri/Cargo.toml"

tauri/config:
- all:
  - changed-files:
    - any-glob-to-any-file: "src-tauri/*.json"

tauri/src:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/src/commands/*"

# Core labels
core/deps:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "package.json"
      - "pnpm-lock.yaml"
      - "src-tauri/Cargo.lock"

core/config:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - ".eslintrc.*"
      - ".gitignore"
      - ".gitmodules"
      - ".npmrc"
      - "*.config.*"
      - "jsconfig.*"
      - ".husky/*"

core/readme:
- all:
  - changed-files:
    - any-glob-to-any-file: "README.md"

# Library specific labels
libs:
- all:
  - changed-files:
    - any-glob-to-any-file: "libs/**/*"

# Types of changes labels
bugfix:
- all:
  - head-branch: ["^fix", "fix/"]

feature:
- all:
  - head-branch: ["^feat", "feat/"]

chore:
- all:
  - head-branch: ["^chore", "chore/"]

refactor:
- all:
  - head-branch: ["^refactor", "refactor/"]

ci:
- all:
  - head-branch: ["^ci", "ci/"]

config:
- all:
  - head-branch: ["^config", "config/"]

docs:
- all:
  - head-branch: ["^docs", "docs/"]

build:
- all:
  - head-branch: ["^build", "build/"]

performance:
- all:
  - head-branch: ["^perf", "perf/"]