# Infra labels
ci:core:
- all:
  - changed-files:
    - any-glob-to-any-file: ".github/**/*"
    - all-globs-to-all-files: '!**/workflows/*'
    - all-globs-to-all-files: '!**/ISSUE_TEMPLATE/*'

ci:workflows:
- all:
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**/*"

ci:templates:
- all:
  - changed-files:
    - any-glob-to-any-file: ".github/ISSUE_TEMPLATE/**/*"

versioning:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "CHANGELOG.md"
      - "latest.json"

notifications:
- all:
  - changed-files:
    - any-glob-to-any-file: "notifications.json"

# Documentation labels
docs:config:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "docs/.gitignore"
      - "docs/*.config.*"
      - "docs/jsconfig.*"

docs:deps:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "docs/package.json"
      - "docs/pnpm-lock.yaml"

docs:site:
- all:
  - changed-files:
    - any-glob-to-any-file: "docs/**/*"

docs:components:
- all:
  - changed-files:
    - any-glob-to-any-file: 
      - "docs/src/components/**/*"
      - "docs/app/**/*"

docs:content:
- all:
  - changed-files:
    - any-glob-to-any-file: "docs/src/content/**/*"

docs:assets:
- all:
  - changed-files:
    - any-glob-to-any-file: "docs/public/**/*"

# React specific labels
ui:components:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/**/*"

ui:states:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/contexts/**/*"

ui:ui:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/ui/**/*"

ui:hooks:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/hooks/**/*"

ui:i18n:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/i18n/**/*"

ui:pages:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/pages/**/*"

ui:styles:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/styles/**/*"

ui:utils:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/utils/**/*"

ui:assets:
- all:
  - changed-files:
    - any-glob-to-any-file: "public/**/*"

# Tauri specific labels
tauri:
- all:
  - changed-files:
    - any-glob-to-any-file: "src-tauri/**/*"
    - all-globs-to-all-files: '!src-tauri/src/**/*'
    - all-globs-to-all-files: '!src-tauri/build.rs'
    - all-globs-to-all-files: '!src-tauri/Cargo.lock'
    - all-globs-to-all-files: '!src-tauri/Cargo.toml'
    - all-globs-to-all-files: '!src-tauri/*.json'

tauri:core:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/build.rs"
      - "src-tauri/src/main.rs"
      - "src-tauri/src/lib.rs"

tauri:deps:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/Cargo.lock"
      - "src-tauri/Cargo.toml"

tauri:config:
- all:
  - changed-files:
    - any-glob-to-any-file: "src-tauri/*.json"

tauri:src:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/src/commands/**/*"

# Core labels
core:deps:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "package.json"
      - "pnpm-lock.yaml"

core:config:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - ".eslintrc.*"
      - ".gitignore"
      - ".gitmodules"
      - ".npmrc"
      - "*.config.*"
      - "jsconfig.*"
      - ".husky/*"
      - "*.yml"

core:docs:
- all:
  - changed-files:
    - any-glob-to-any-file: "README.md"

# Library specific labels
libs:
- all:
  - changed-files:
    - any-glob-to-any-file: 
      - "libs/**/*"
      - "libs/**"

# Types of changes labels
bugfix:
- all:
  - head-branch: ["^fix", "fix/"]

feature:
- all:
  - head-branch: ["^feat", "feat/"]

chore:
- all:
  - head-branch: ["^chore", "chore/"]

refactor:
- all:
  - head-branch: ["^refactor", "refactor/"]

ci:
- all:
  - head-branch: ["^ci", "ci/"]

config:
- all:
  - head-branch: ["^config", "config/"]

docs:
- all:
  - head-branch: ["^docs", "docs/"]

build:
- all:
  - head-branch: ["^build", "build/"]

performance:
- all:
  - head-branch: ["^perf", "perf/"]