# Infra labels
github/workflows:
- all:
  - changed-files:
    - any-glob-to-any-file: ".github/workflows/**/*"

github/templates:
- all:
  - changed-files:
    - any-glob-to-any-file: ".github/ISSUE_TEMPLATE/**/*"

release:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "CHANGELOG.md"
      - "latest.json"

# Documentation labels
docs/site:
- all:
  - changed-files:
    - any-glob-to-any-file: "docs/**/*"

# React specific labels
react:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/**/*"

react/components:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/**/*"

react/states:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/contexts/**/*"

react/ui:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/components/ui/**/*"

react/hooks:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/hooks/**/*"

react/i18n:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/i18n/**/*"

react/pages:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/pages/**/*"

react/styles:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/styles/**/*"

react/utils:
- all:
  - changed-files:
    - any-glob-to-any-file: "src/utils/**/*"

react/assets:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src/assets/**/*"
      - "public/**/*"

# Tauri specific labels
tauri:
- all:
  - changed-files:
    - any-glob-to-any-file: "src-tauri/**/*"

tauri/core:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/build.rs"
      - "src-tauri/src/main.rs"
      - "src-tauri/src/lib.rs"

tauri/deps:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/Cargo.lock"
      - "src-tauri/Cargo.toml"

tauri/config:
- all:
  - changed-files:
    - any-glob-to-any-file: "src-tauri/*.json"

tauri/src:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "src-tauri/src/commands/*"

# Dependencies labels
dependencies:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - "package.json"
      - "pnpm-lock.yaml"
      - "src-tauri/Cargo.lock"

# Types of changes labels
bugfix:
- all:
  - head-branch: ["^fix", "fix/"]

feature:
- all:
  - head-branch: ["^feat", "feat/"]

chore:
- all:
  - head-branch: ["^chore", "chore/"]

refactor:
- all:
  - head-branch: ["^refactor", "refactor/"]

ci:
- all:
  - head-branch: ["^ci", "ci/"]

config:
- all:
  - head-branch: ["^config", "config/"]

docs:
- all:
  - head-branch: ["^docs", "docs/"]

build:
- all:
  - head-branch: ["^build", "build/"]

performance:
- all:
  - head-branch: ["^perf", "perf/"]