// eslint-disable-next-line @typescript-eslint/no-require-imports
const { heroui } = require('@heroui/react')

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      width: {
        calc: 'calc(100vw - 250px)',
      },
      height: {
        calc: 'calc(100vh - 36px)',
      },
      maxHeight: {
        calc: 'calc(100vh - 36px)',
      },
      minHeight: {
        calc: 'calc(100vh - 36px)',
      },
    },
  },
  darkMode: 'class',
  plugins: [
    heroui({
      themes: {
        light: {
          colors: {
            'base': '#f6f6f6',
            'container': '#f7f7f7',
            'containerhover': '#f5f5f5',
            'dynamic': '#009FC2',
            'dynamic-hover': '#0090af',
            'btn-text': '#ffffff',
            'btn-text-alt': '#000000',
            'btn-secondary': '#2c2c2c',
            'content': '#000000',
            'offwhite': '#ebebeb',
            'altwhite': '#5c6674',
            'header-hover': '#000000',
            'titlehover': '#ececec',
            'sidebar': '#ffffff',
            'item-active': '#d9d9d9',
            'item-hover': '#e4e4e4',
            'search': '#d9d9d9',
            'searchhover': '#ececec',
            'searchborder': '#dcdcdc',
            'button-text': '#ffffff',
            'border': '#e3e3e3',
            'input': '#d9d9d9',
            'inputhover': '#ececec',
            'switch': '#e5e5e5',
            'modalheader': '#ffffff',
            'modalbody': '#fafafa',
            'modalbody-hover': '#f4f4f4',
            'modalfooter': '#ffffff',
            'tablehead': '#efefef',
            'tablerow': '#f1f1f1',
            'tablerowalt': '#f7f7f7',
            'link': '#006fee',
            'linkhover': '#4b82bb',
            'alert': '#fafafa',
            'tab-panel': '#ffffff',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
        dark: {
          colors: {
            'base': '#0D0F12',
            'container': '#161616',
            'containerhover': '#252525',
            'dynamic': '#009FC2',
            'dynamic-hover': '#0090af',
            'btn-text': '#000000',
            'btn-text-alt': '#ffffff',
            'btn-secondary': '#ebebeb',
            'content': '#ffffff',
            'offwhite': '#ebebeb',
            'altwhite': '#a9a9a9',
            'header-hover': '#ffffff',
            'sidebar': '#121316',
            'item-active': '#47484B',
            'item-hover': '#2d2e31',
            'search': '#28292C',
            'searchhover': '#333436',
            'searchborder': '#3E3F41',
            'button-text': '#ffffff',
            'border': '#272727',
            'input': '#191B1E',
            'inputhover': '#24262a',
            'switch': '#2e3237',
            'modalheader': '#121212',
            'modalbody': '#171717',
            'modalbody-hover': '#212427',
            'modalfooter': '#121212',
            'tablehead': '#131313',
            'tablerow': '#1a1a1a',
            'tablerowalt': '#161616',
            'alert': '#1f2125',
            'tab-panel': '#191B1E',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
        slate: {
          colors: {
            'base': '#16181C',
            'container': '#16181C',
            'containerhover': '#1c1d22',
            'dynamic': '#009FC2',
            'dynamic-hover': '#0090af',
            'btn-text': '#000000',
            'btn-text-alt': '#ffffff',
            'btn-secondary': '#ebebeb',
            'content': '#ffffff',
            'offwhite': '#ebebeb',
            'altwhite': '#a9a9a9',
            'header-hover': '#ffffff',
            'titlehover': '#35383f',
            'sidebar': '#26292F',
            'item-active': '#4d515a',
            'item-hover': '#35383f',
            'search': '#3b3f49',
            'searchhover': '#444852',
            'searchborder': '#515253',
            'button-text': '#ffffff',
            'border': '#2a2a2d',
            'input': '#202328',
            'inputhover': '#232529',
            'switch': '#424853',
            'modalheader': '#26292F',
            'modalbody': '#22252a',
            'modalbody-hover': '#1c1e23',
            'modalfooter': '#26292F',
            'tablehead': '#22252a',
            'tablerow': '#16181C',
            'tablerowalt': '#1c1d22',
            'link': '#5a95d3',
            'linkhover': '#4b82bb',
            'alert': '#1f2125',
            'tab-panel': '#202328',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
      },
    }),
  ],
}
