const { heroui } = require('@heroui/react')

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  safelist: ['break-inside-avoid'],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-bg': 'var(--gradient-bg)',
        'gradient-alt': 'var(--gradient-alt)',
      },
      width: {
        calc: 'calc(100vw - 250px)',
      },
      height: {
        calc: 'calc(100vh - 36px)',
      },
      maxHeight: {
        calc: 'calc(100vh - 36px)',
      },
      minHeight: {
        calc: 'calc(100vh - 36px)',
      },
      animation: {
        'skew-scroll': 'skew-scroll 30s linear infinite',
      },
      keyframes: {
        'skew-scroll': {
          '0%': {
            transform: 'rotatex(20deg) rotateZ(-20deg) skewX(20deg) translateZ(0) translateY(0)',
          },
          '100%': {
            transform:
              'rotatex(20deg) rotateZ(-20deg) skewX(20deg) translateZ(0) translateY(-100%)',
          },
        },
      },
    },
  },
  darkMode: 'class',
  plugins: [
    heroui({
      themes: {
        dark: {
          colors: {
            'base': '#000000ff',
            'dynamic': '#7ac2e3ff',
            'dynamic-hover': '#5aa3c4ff',
            'btn-text': '#000000',
            'btn-secondary': '#ebebeb',
            'btn-achievement-header': '#6f6f6f52',
            'btn-achievement-header-hover': '#58585852',
            'content': '#ffffff',
            'altwhite': '#a9a9a9',
            'header-hover': '#ffffff',
            'sidebar': '#151515ff',
            'item-active': '#ffffff11',
            'item-hover': '#ffffff0c',
            'search': '#6d6d6d42',
            'border': '#1f1f1fff',
            'input': '#333333ff',
            'inputhover': '#272727ff',
            'switch': '#333333ff',
            'tab-panel': '#00000058',
            'popover': '#101010ff',
            'achievement-main': '#1c1c1ccc',
            'achievement-footer': '#1f1f1fcc',
            'stats-input': '#333333ff',
            'stats-inputhover': '#272727ff',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
        blue: {
          colors: {
            'base': '#070a0f',
            'dynamic': '#61b7f0ff',
            'dynamic-hover': '#47a8ef',
            'btn-text': '#070a0f',
            'btn-secondary': '#d9eaff',
            'btn-achievement-header': '#3e6a9e33',
            'btn-achievement-header-hover': '#3e6a9e55',
            'content': '#ffffff',
            'altwhite': '#c0cddd',
            'header-hover': '#ffffff',
            'sidebar': '#0d1117',
            'item-active': '#57baff22',
            'item-hover': '#57baff11',
            'search': '#47a8ef33',
            'border': '#18202b',
            'input': '#1b232dff',
            'inputhover': '#182029ff',
            'switch': '#202934ff',
            'tab-panel': '#070a0f55',
            'popover': '#0c1016',
            'achievement-main': '#18202bcc',
            'achievement-footer': '#18202be6',
            'stats-input': '#232c38ff',
            'stats-inputhover': '#1d252fff',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
        red: {
          colors: {
            'base': '#0c0709',
            'dynamic': '#ff4f5e',
            'dynamic-hover': '#e83d4b',
            'btn-text': '#0c0709',
            'btn-secondary': '#ffd7db',
            'btn-achievement-header': '#a33d4933',
            'btn-achievement-header-hover': '#a33d4955',
            'content': '#ffffff',
            'altwhite': '#d3b8bd',
            'header-hover': '#ffffff',
            'sidebar': '#130c0e',
            'item-active': '#ff4f5e22',
            'item-hover': '#ff4f5e11',
            'search': '#e83d4b33',
            'border': '#241518',
            'input': '#23181aff',
            'inputhover': '#1d1315ff',
            'switch': '#2a1d20ff',
            'tab-panel': '#0c070955',
            'popover': '#10090b',
            'achievement-main': '#241518cc',
            'achievement-footer': '#241518e6',
            'stats-input': '#312325ff',
            'stats-inputhover': '#2c1f21ff',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
        purple: {
          colors: {
            'base': '#0a0910',
            'dynamic': '#b387ff',
            'dynamic-hover': '#a372f7',
            'btn-text': '#0a0910',
            'btn-secondary': '#e9e1f7',
            'btn-achievement-header': '#7e5fae33',
            'btn-achievement-header-hover': '#7e5fae55',
            'content': '#ffffff',
            'altwhite': '#cbbedd',
            'header-hover': '#ffffff',
            'sidebar': '#100c13ff',
            'item-active': '#b387ff22',
            'item-hover': '#b387ff11',
            'search': '#a372f733',
            'border': '#221c2f',
            'input': '#1e1a27ff',
            'inputhover': '#1a1723ff',
            'switch': '#231f2eff',
            'tab-panel': '#0a091055',
            'popover': '#0f0d15',
            'achievement-main': '#221c2fcc',
            'achievement-footer': '#221c2fe6',
            'stats-input': '#2a2436ff',
            'stats-inputhover': '#241f2fff',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
        pink: {
          colors: {
            'base': '#0a0910',
            'dynamic': '#ff6ecf',
            'dynamic-hover': '#eb5abd',
            'btn-text': '#0a0910',
            'btn-secondary': '#fde3f5',
            'btn-achievement-header': '#c7449a33',
            'btn-achievement-header-hover': '#c7449a55',
            'content': '#ffffff',
            'altwhite': '#e0bfd7',
            'header-hover': '#ffffff',
            'sidebar': '#130c11ff',
            'item-active': '#ff6ecf22',
            'item-hover': '#ff6ecf11',
            'search': '#eb5abd33',
            'border': '#2b1b28',
            'input': '#2d1f2eff',
            'inputhover': '#281b29ff',
            'switch': '#2c1f2eff',
            'tab-panel': '#0a091055',
            'popover': '#0f0d15',
            'achievement-main': '#2b1b28cc',
            'achievement-footer': '#2b1b28e6',
            'stats-input': '#332436ff',
            'stats-inputhover': '#2e2031ff',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
        gold: {
          colors: {
            'base': '#050505',
            'dynamic': '#fccf5bff',
            'dynamic-hover': '#ebc671',
            'btn-text': '#0b0b0b',
            'btn-secondary': '#fff5dd',
            'btn-achievement-header': '#b8924a33',
            'btn-achievement-header-hover': '#b8924a55',
            'content': '#ffffff',
            'altwhite': '#e8d9b8',
            'header-hover': '#ffffff',
            'sidebar': '#0a0a0a',
            'item-active': '#f6d88922',
            'item-hover': '#f6d88911',
            'search': '#ebc67133',
            'border': '#2b2213',
            'input': '#3a3221ff',
            'inputhover': '#332c1dff',
            'switch': '#463d29ff',
            'tab-panel': '#05050555',
            'popover': '#0a0a0a',
            'achievement-main': '#2b2213cc',
            'achievement-footer': '#2b2213e6',
            'stats-input': '#3a3221ff',
            'stats-inputhover': '#332c1dff',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
        black: {
          colors: {
            'base': '#000000',
            'dynamic': '#dadadaff',
            'dynamic-hover': '#cdcdcdff',
            'btn-text': '#000000',
            'btn-secondary': '#f2f2f2',
            'btn-achievement-header': '#ffffff1a',
            'btn-achievement-header-hover': '#ffffff33',
            'content': '#ffffff',
            'altwhite': '#bfbfbf',
            'header-hover': '#ffffff',
            'sidebar': '#000000',
            'item-active': '#ffffff0f',
            'item-hover': '#ffffff08',
            'search': '#ffffff1a',
            'border': '#1a1a1a',
            'input': '#111111ff',
            'inputhover': '#0c0c0cff',
            'switch': '#161616ff',
            'tab-panel': '#00000088',
            'popover': '#050505',
            'achievement-main': '#1a1a1acc',
            'achievement-footer': '#1a1a1ae6',
            'stats-input': '#212121ff',
            'stats-inputhover': '#1b1b1bff',
            'primary': {
              DEFAULT: '#2c7adb',
            },
            'secondary': {
              DEFAULT: '#137eb5',
            },
            'danger': {
              DEFAULT: '#ef4444',
              foreground: '#fff',
            },
          },
        },
      },
    }),
  ],
}

export default config
