name: Feature Request
description: Suggest an idea for this project
title: "Title"
labels: ["feature request"]
assignees:
  - "zevnda"
body:
  - type: textarea
    id: idea
    attributes:
      label: Describe the feature
      placeholder: Include as much information as possible, how could it be implemented, what will it do, how would it benefit you and other users, etc
    validations:
      required: true
  - type: dropdown
    id: sgi-branch
    attributes:
      label: Which branch of SGI?
      options:
        - "Base"
        - "CLI + WebUI"
    validations:
      required: true
  - type: input
    id: issue
    attributes:
      label: Is your feature request related to an issue?
      placeholder: "Yes, this should fix issue #7"
    validations:
      required: false
