name: Feature Request
description: Suggest an idea for this project
labels: ["feature request"]
assignees:
  - "zevnda"
body:
  - type: textarea
    id: feature-details
    attributes:
      label: Feature Description and Purpose
      description: Provide a detailed overview of the feature. Explain what it will do, the problem it solves, potential use cases, and how it benefits you or others. Include examples if possible
    validations:
      required: true
      
  - type: textarea
    id: issue
    attributes:
      label: Related Issues
      description: If your request addresses an open issue, link to it here and explain how it resolves the issue
      placeholder: "This is related to #7 and will fix it by..."

  - type: checkboxes
    id: contributions
    attributes:
      label: Contribution
      options:
        - label: I would like to work on this myself and will submit a pull request
