name: Issue/Bug Report
description: Report a bug or issue
labels: ["bug"]
assignees:
  - "zevnda"
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Pre-report Checklist
      options:
        - label: I have searched for similar [open/closed issues](https://github.com/zevnda/steam-game-idler/issues)
          required: true
        - label: I have checked the [FAQ page](https://steamgameidler.vercel.app/faq) for my issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Provide a clear and detailed description of the issue. Include any relevant screenshots, videos, or error messages
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide the exact steps to reproduce this issue. If unsure, describe what you were doing when the issue occurred
    validations:
      required: true
      
  - type: textarea
    id: log-file
    attributes:
      label: Log File
      description: Attach your log file from `C:\Users\<user>\AppData\Roaming\steam-game-idler`
    validations:
      required: true

  - type: textarea
    id: export-data
    attributes:
      label: Exported Data
      description: Export your data by going to Settings > Export Data and then pasting it here
      render: json
    validations:
      required: true
