name: Crowdin

on:
  # schedule:
    # - cron: "0 * * * *" # Uncomment this line to run every hour
  workflow_dispatch:

jobs:
  download-translations:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Download Crowdin Translations
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          download_sources: true
          download_translations: true
          
          crowdin_branch_name: main
          export_only_approved: true
          skip_untranslated_files: true
          
          localization_branch_name: i18n/crowdin
          create_pull_request: true
          pull_request_title: "chore(i18n): pull translations from crowdin"
          pull_request_base_branch_name: "main"
          
          commit_message: "chore(i18n): pull translations from crowdin"
          
          github_user_name: "crowdin-action"
          github_user_email: "crowdin-action@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}