name: Labeler History
on:
  workflow_dispatch:

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github

    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: '.github/labeler.yml'
        sync-labels: true
        pr-number: |
          202
          201
          200
          199
          198
          197
          196
          195
          194
          193
          192
          191
          190
          189
          188
          187
          186
          185
          184
          182
          181
          180
          179
          178
          177
          176
          175
          174
          173
          172
          171
          170
          169
          168
          167
          166
          165
          164
          163
          162
          161
          160
          159
          158
          157
          156