name: Update Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  update-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        id: check_title
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ ^chore\(version\):\ bump\ to\ [0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "match=true" >> $GITHUB_ENV
          else
            echo "match=false" >> $GITHUB_ENV
          fi

      - name: Fail if PR Title is Incorrect
        if: env.match == 'false'
        run: echo "PR title format is incorrect" && exit 1

      - name: Extract Release Tag
        id: extract_tag
        run: |
          echo "tag=$(echo '${{ github.event.pull_request.title }}' | sed -E 's/^chore\(version\): bump to ([0-9]+\.[0-9]+\.[0-9]+)$/\1/')" >> $GITHUB_ENV

      - name: Get Release ID
        id: get_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          prerelease: false